/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

/*
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t *pPortAOutReg =  (uint32_t*)0x40020014; */

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrlReg   = (RCC_AHB1ENR_t*) 0x40023830;
	GPIOx_MODE_t  volatile *const pPortAModeReg = (GPIOx_MODE_t*) 0x40020000;
	GPIOx_ODR_t   volatile *const pPortAOutReg  = (GPIOx_ODR_t*) 0x40020014;

	//1. enable the clock for GPOIA peripheral in the AHB1ENR (SET the 0th bit position)
	pClkCtrlReg->gpioa_en = 1;


	//2. configure the mode of the IO pin as output
	pPortAModeReg->pin_5 = 1;

	while(1)
	{
		//Set 5th bit of the output data register to make I/O pin-5 as HIGH
		pPortAOutReg->pin_5  = 1;

		//introduce small human observable delay
		//This loop executes for 300K times
		for(uint32_t i=0 ; i < 300000 ; i++ );

		//Reset 5th bit of the output data register to make I/O pin-5 as LOW
		pPortAOutReg->pin_5  = 0;

		for(uint32_t i=0 ; i < 300000 ; i++ );
	}


	for(;;);
}
