/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdio.h>

struct DataSet
{
	char  data1 ;
	int   data2 ;
	char  data3 ;
	short data4 ;
}__attribute__((packed));


struct DataSet data ; //this consumes 12 bytes in memory(RAM)

int main(void)
{

	data.data1 = 0xAA;
	data.data2 = 0xFFFFEEEE;
	data.data3 = 0x55;
	data.data4 = 0xA5A5;

	printf("data.data1 = %X\n",data.data1);
	printf("data.data2 = %X\n",data.data2);
	printf("data.data3 = %X\n",data.data3);
	printf("data.data4 = %X\n",data.data4);

	for(;;);
}
